//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.22 at 06:41:53 PM CEST 
//


package bddm.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DTO_PresekZaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DTO_PresekZaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="brojRacuna" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="brojPreseka" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="prethodnoStanje" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="brPromenaUKorist" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ukupnoUKorist" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="brPromenaNaTeret" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ukupnoNaTeret" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="novoStanje" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="stavke" type="{http://bddm/dto/soap}DTO_PresekStavka" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DTO_PresekZaglavlje", propOrder = {
    "brojRacuna",
    "datum",
    "brojPreseka",
    "prethodnoStanje",
    "brPromenaUKorist",
    "ukupnoUKorist",
    "brPromenaNaTeret",
    "ukupnoNaTeret",
    "novoStanje",
    "stavke"
})
public class DTOPresekZaglavlje {

    @XmlElement(required = true)
    protected String brojRacuna;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    protected int brojPreseka;
    protected float prethodnoStanje;
    protected int brPromenaUKorist;
    protected float ukupnoUKorist;
    protected int brPromenaNaTeret;
    protected float ukupnoNaTeret;
    protected float novoStanje;
    @XmlElement(required = true)
    protected List<DTOPresekStavka> stavke;

    /**
     * Gets the value of the brojRacuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojRacuna() {
        return brojRacuna;
    }

    /**
     * Sets the value of the brojRacuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojRacuna(String value) {
        this.brojRacuna = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the brojPreseka property.
     * 
     */
    public int getBrojPreseka() {
        return brojPreseka;
    }

    /**
     * Sets the value of the brojPreseka property.
     * 
     */
    public void setBrojPreseka(int value) {
        this.brojPreseka = value;
    }

    /**
     * Gets the value of the prethodnoStanje property.
     * 
     */
    public float getPrethodnoStanje() {
        return prethodnoStanje;
    }

    /**
     * Sets the value of the prethodnoStanje property.
     * 
     */
    public void setPrethodnoStanje(float value) {
        this.prethodnoStanje = value;
    }

    /**
     * Gets the value of the brPromenaUKorist property.
     * 
     */
    public int getBrPromenaUKorist() {
        return brPromenaUKorist;
    }

    /**
     * Sets the value of the brPromenaUKorist property.
     * 
     */
    public void setBrPromenaUKorist(int value) {
        this.brPromenaUKorist = value;
    }

    /**
     * Gets the value of the ukupnoUKorist property.
     * 
     */
    public float getUkupnoUKorist() {
        return ukupnoUKorist;
    }

    /**
     * Sets the value of the ukupnoUKorist property.
     * 
     */
    public void setUkupnoUKorist(float value) {
        this.ukupnoUKorist = value;
    }

    /**
     * Gets the value of the brPromenaNaTeret property.
     * 
     */
    public int getBrPromenaNaTeret() {
        return brPromenaNaTeret;
    }

    /**
     * Sets the value of the brPromenaNaTeret property.
     * 
     */
    public void setBrPromenaNaTeret(int value) {
        this.brPromenaNaTeret = value;
    }

    /**
     * Gets the value of the ukupnoNaTeret property.
     * 
     */
    public float getUkupnoNaTeret() {
        return ukupnoNaTeret;
    }

    /**
     * Sets the value of the ukupnoNaTeret property.
     * 
     */
    public void setUkupnoNaTeret(float value) {
        this.ukupnoNaTeret = value;
    }

    /**
     * Gets the value of the novoStanje property.
     * 
     */
    public float getNovoStanje() {
        return novoStanje;
    }

    /**
     * Sets the value of the novoStanje property.
     * 
     */
    public void setNovoStanje(float value) {
        this.novoStanje = value;
    }

    /**
     * Gets the value of the stavke property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavke property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavke().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DTOPresekStavka }
     * 
     * 
     */
    public List<DTOPresekStavka> getStavke() {
        if (stavke == null) {
            stavke = new ArrayList<DTOPresekStavka>();
        }
        return this.stavke;
    }

}
