//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.22 at 06:41:53 PM CEST 
//


package bddm.dto.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bddm.dto.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bddm.dto.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PresekRequest }
     * 
     */
    public PresekRequest createPresekRequest() {
        return new PresekRequest();
    }

    /**
     * Create an instance of {@link DTOPresekZahtev }
     * 
     */
    public DTOPresekZahtev createDTOPresekZahtev() {
        return new DTOPresekZahtev();
    }

    /**
     * Create an instance of {@link UplatnicaRequest }
     * 
     */
    public UplatnicaRequest createUplatnicaRequest() {
        return new UplatnicaRequest();
    }

    /**
     * Create an instance of {@link DTOUplatnica }
     * 
     */
    public DTOUplatnica createDTOUplatnica() {
        return new DTOUplatnica();
    }

    /**
     * Create an instance of {@link UplatnicaResponse }
     * 
     */
    public UplatnicaResponse createUplatnicaResponse() {
        return new UplatnicaResponse();
    }

    /**
     * Create an instance of {@link MockType }
     * 
     */
    public MockType createMockType() {
        return new MockType();
    }

    /**
     * Create an instance of {@link PresekResponse }
     * 
     */
    public PresekResponse createPresekResponse() {
        return new PresekResponse();
    }

    /**
     * Create an instance of {@link DTOPresekZaglavlje }
     * 
     */
    public DTOPresekZaglavlje createDTOPresekZaglavlje() {
        return new DTOPresekZaglavlje();
    }

    /**
     * Create an instance of {@link DTOPresekStavka }
     * 
     */
    public DTOPresekStavka createDTOPresekStavka() {
        return new DTOPresekStavka();
    }

}
