//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.22 at 06:41:53 PM CEST 
//


package bddm.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uplatnica" type="{http://bddm/dto/soap}DTO_PresekZaglavlje"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uplatnica"
})
@XmlRootElement(name = "PresekResponse")
public class PresekResponse {

    @XmlElement(required = true)
    protected DTOPresekZaglavlje uplatnica;

    /**
     * Gets the value of the uplatnica property.
     * 
     * @return
     *     possible object is
     *     {@link DTOPresekZaglavlje }
     *     
     */
    public DTOPresekZaglavlje getUplatnica() {
        return uplatnica;
    }

    /**
     * Sets the value of the uplatnica property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTOPresekZaglavlje }
     *     
     */
    public void setUplatnica(DTOPresekZaglavlje value) {
        this.uplatnica = value;
    }

}
